### ISSUE TITLE
Directory

### ISSUE THREAD

**Issue by Sattishh** [jahaanjain/meme-creator#1]
Hey! I was very interested in your API in npmjs but I was wondering what if I didnt want to save it into directory and rather just have it as JSON url. Any ideas for that?

**Comment by jahaanjain** [comment]
You could save the file into a public directory, and use express to share the link to the directory, something like this:

```
memeCreator(options, function(res, error) {
    if(error) throw new Error(error)
    console.log('You can view your meme by going to https://mydomain.com/' + res.fileName.split('/').pop());
});
```

**Comment by Sattishh** [comment]
Ah okay. Thanks!
