### ISSUE TITLE
Publish new version to npm with peerDependencies in package.json

### ISSUE THREAD

**Issue by karlhorky** [jahaanjain/meme-creator#3]
Hi, thanks for this package!

Would it be possible to publish a new version to npm with the change in the pull request that @Josehower made for `peerDependencies`?

https://github.com/jahaanjain/meme-creator/pull/2

**Comment by jahaanjain** [comment]
Yes, I've just updated it on npmjs.

**Comment by karlhorky** [comment]
Great, thanks!
